'use client';
import { useState } from 'react';
import { formatDate } from '@/lib/utils';

export default function WeeklyReport({ project, onClose }) {
  const [report, setReport] = useState(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');
  const [copied, setCopied] = useState(false);

  const generateReport = async () => {
    setLoading(true);
    setError('');
    try {
      const resp = await fetch('/api/weekly-report', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ project }),
      });
      if (!resp.ok) throw new Error((await resp.json()).error || 'Failed');
      setReport(await resp.json());
    } catch (err) {
      setError(err.message);
    } finally {
      setLoading(false);
    }
  };

  const getReportText = () => {
    if (!report) return '';
    return `WEEKLY STATUS REPORT — ${project.name}
Week Ending: ${report.weekEnding}

EXECUTIVE SUMMARY
${report.executiveSummary}

PROGRESS THIS WEEK
${(report.progressThisWeek || []).map((p) => `• ${p}`).join('\n')}

UPCOMING NEXT WEEK
${(report.upcomingNextWeek || []).map((p) => `• ${p}`).join('\n')}

DELAYS & RISKS
${(report.delaysAndRisks || []).map((p) => `• ${p}`).join('\n') || '• None'}

CHANGE ORDERS
${(report.changeOrders || []).map((p) => `• ${p}`).join('\n') || '• None'}

BUDGET STATUS
Original: $${report.budgetStatus?.original?.toLocaleString() || 'N/A'}
Projected: $${report.budgetStatus?.projected?.toLocaleString() || 'N/A'}
Variance: ${report.budgetStatus?.variancePct || 0}%

SCHEDULE STATUS
Original End: ${report.scheduleStatus?.originalEnd || 'N/A'}
Projected End: ${report.scheduleStatus?.projectedEnd || 'N/A'}
Variance: ${report.scheduleStatus?.varianceDays || 0} days

KEY DECISIONS NEEDED
${(report.keyDecisionsNeeded || []).map((p) => `• ${p}`).join('\n') || '• None'}

2-WEEK LOOKAHEAD
${(report.lookahead2Week || []).map((p) => `• ${p}`).join('\n')}

— Generated by TopOut`;
  };

  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(getReportText());
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch {}
  };

  const handleEmail = () => {
    const subject = encodeURIComponent(`Weekly Report — ${project.name} — ${report.weekEnding}`);
    const body = encodeURIComponent(getReportText());
    window.open(`mailto:?subject=${subject}&body=${body}`);
  };

  const handlePrint = () => window.print();

  return (
    <>
      <div className="fixed inset-0 bg-[#0b1326]/80 backdrop-blur-md z-[60]" onClick={onClose} />
      <div className="fixed inset-y-0 right-0 w-full max-w-2xl bg-surface z-[70] flex flex-col shadow-2xl animate-slide-left">
        {/* Header */}
        <header className="px-6 py-6 flex justify-between items-start border-b border-outline-variant/20">
          <div>
            <h2 className="text-2xl font-extrabold tracking-tighter uppercase font-headline text-on-surface">
              Weekly Report
            </h2>
            <p className="text-primary font-bold text-xs tracking-widest mt-1 uppercase">{project.name}</p>
          </div>
          <button onClick={onClose} className="bg-surface-container-highest p-2 hover:bg-primary hover:text-surface transition-colors">
            <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
              <path d="M18 6L6 18M6 6l12 12" />
            </svg>
          </button>
        </header>

        <div className="flex-1 overflow-y-auto p-6 space-y-6">
          {!report && !loading && (
            <div className="text-center py-12">
              <div className="w-16 h-16 bg-surface-container-highest flex items-center justify-center mx-auto mb-4">
                <svg width="28" height="28" viewBox="0 0 24 24" fill="none" stroke="#ffc174" strokeWidth="2">
                  <path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z" />
                  <polyline points="14 2 14 8 20 8" />
                </svg>
              </div>
              <p className="text-secondary text-sm mb-6">Generate an AI-powered weekly status report from your schedule data, daily logs, and delay history.</p>
              {error && <p className="text-error text-sm mb-4">{error}</p>}
              <button onClick={generateReport} className="machine-gradient text-surface-container-lowest font-headline font-extrabold text-sm uppercase tracking-[0.2em] px-8 py-4 active:scale-95 transition-transform">
                Generate Report
              </button>
            </div>
          )}

          {loading && (
            <div className="text-center py-12 animate-fade-in">
              <div className="w-6 h-6 border-2 border-transparent border-t-primary rounded-full mx-auto mb-4 animate-spin" />
              <p className="text-secondary text-sm font-bold uppercase tracking-widest">Analyzing project data...</p>
            </div>
          )}

          {report && (
            <div className="space-y-6 print:text-black print:bg-white" id="report-content">
              {/* Print header */}
              <div className="hidden print:block text-center mb-8">
                <h1 className="text-2xl font-bold">TOPOUT.</h1>
                <p className="text-lg">{project.name}</p>
                <p>Week Ending: {report.weekEnding}</p>
              </div>

              {/* Executive Summary */}
              <section className="bg-surface-container-low p-5 border-l-4 border-primary">
                <h3 className="text-[10px] font-black text-primary tracking-widest uppercase mb-2">Executive Summary</h3>
                <p className="text-sm text-on-surface leading-relaxed">{report.executiveSummary}</p>
              </section>

              {/* Progress + Upcoming */}
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                <ReportSection title="Progress This Week" items={report.progressThisWeek} />
                <ReportSection title="Upcoming Next Week" items={report.upcomingNextWeek} />
              </div>

              {/* Status Cards */}
              <div className="grid grid-cols-2 gap-px bg-outline-variant/10">
                <div className="bg-surface-container-low p-4">
                  <p className="text-[10px] font-bold text-secondary uppercase tracking-widest mb-1">Budget</p>
                  <p className="text-lg font-black font-headline text-on-surface">
                    ${(report.budgetStatus?.projected || 0).toLocaleString()}
                  </p>
                  <p className={`text-[10px] font-bold ${(report.budgetStatus?.variancePct || 0) > 0 ? 'text-error' : 'text-tertiary'}`}>
                    {report.budgetStatus?.variancePct > 0 ? '+' : ''}{report.budgetStatus?.variancePct || 0}% variance
                  </p>
                </div>
                <div className="bg-surface-container-low p-4">
                  <p className="text-[10px] font-bold text-secondary uppercase tracking-widest mb-1">Schedule</p>
                  <p className="text-lg font-black font-headline text-on-surface">{report.scheduleStatus?.projectedEnd || 'N/A'}</p>
                  <p className={`text-[10px] font-bold ${(report.scheduleStatus?.varianceDays || 0) > 0 ? 'text-error' : 'text-tertiary'}`}>
                    {(report.scheduleStatus?.varianceDays || 0) > 0 ? `+${report.scheduleStatus.varianceDays}d behind` : 'On schedule'}
                  </p>
                </div>
              </div>

              <ReportSection title="Delays & Risks" items={report.delaysAndRisks} color="error" />
              <ReportSection title="Key Decisions Needed" items={report.keyDecisionsNeeded} color="primary" />
              <ReportSection title="2-Week Lookahead" items={report.lookahead2Week} />

              {/* Actions */}
              <div className="flex flex-wrap gap-3 pt-4">
                <button onClick={handleCopy} className={`flex-1 py-3 font-headline font-bold text-[10px] uppercase tracking-widest transition-colors ${copied ? 'bg-tertiary/20 text-tertiary' : 'bg-surface-container-highest text-on-surface hover:bg-surface-container-high'}`}>
                  {copied ? 'Copied' : 'Copy Text'}
                </button>
                <button onClick={handleEmail} className="flex-1 py-3 bg-surface-container-highest text-on-surface font-headline font-bold text-[10px] uppercase tracking-widest hover:bg-surface-container-high">
                  Email
                </button>
                <button onClick={handlePrint} className="flex-1 py-3 machine-gradient text-surface-container-lowest font-headline font-bold text-[10px] uppercase tracking-widest active:scale-95 transition-transform">
                  Print / PDF
                </button>
              </div>
            </div>
          )}
        </div>
      </div>
    </>
  );
}

function ReportSection({ title, items, color = 'secondary' }) {
  if (!items || items.length === 0) return null;
  const borderColors = { error: 'border-error', primary: 'border-primary', secondary: 'border-outline-variant/20' };
  return (
    <section className={`bg-surface-container-low p-5 border-l-4 ${borderColors[color] || borderColors.secondary}`}>
      <h3 className="text-[10px] font-black text-secondary tracking-widest uppercase mb-3">{title}</h3>
      <ul className="space-y-2">
        {items.map((item, i) => (
          <li key={i} className="text-xs text-on-surface leading-relaxed flex gap-2">
            <span className="text-secondary flex-shrink-0 mt-0.5">&bull;</span>
            {item}
          </li>
        ))}
      </ul>
    </section>
  );
}
